BASE_URL = 'https://review-api.udacity.com/api/v1/'
ASSIGNED_URL = BASE_URL + 'me/submissions/assigned.json'
ASSIGNED_COUNT_URL = BASE_URL + 'me/submissions/assigned_count.json'
CERTIFICATIONS_URL = BASE_URL + 'me/certifications.json'
CRITIQUES_URL = BASE_URL + 'submissions/{}/critiques.json'
ME_URL = BASE_URL + 'me.json'
RUBRICS_URL = BASE_URL + 'rubrics/{}.json'
SUBMISSIONS_URL = BASE_URL + 'submissions/{}.json'
SUB_REQ_ME_URL = BASE_URL + 'me/submission_requests.json'
SUB_REQ_CREATE_URL = BASE_URL + 'submission_requests.json'
SUB_REQ_INSTANCE_URL = BASE_URL + 'submission_requests/{}.json'
SUB_REQ_REFRESH_URL = BASE_URL + 'submission_requests/{}/refresh.json'

SUBMISSION_URL = 'https://review.udacity.com/#!/submissions/{}'
