# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('topic', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('awesome', 'awesome'), ('nitpick', 'nitpick'), ('critical', 'critical')], max_length=8)),
                ('retrievals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('topic', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed')], max_length=6)),
                ('retrievals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed')], max_length=6)),
                ('retrievals', models.IntegerField(default=0)),
            ],
        ),
    ]
