# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 22:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('projects', django.contrib.postgres.fields.jsonb.JSONField()),
                ('udacity_jwt', models.TextField()),
            ],
        ),
    ]
